version: "3.4"

services:
  server:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.debug
    env_file:
      - .env
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - 8000:8000
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DATABASE} -U $${POSTGRES_USER}"
        ]
      interval: 1s
      timeout: 3s
      retries: 10
  cache:
    image: redis:6.2.10
    environment:
      REDIS_MAXMEMORY: ${REDIS_MAXMEMORY}
      REDIS_MAXMEMORY_POLICY: ${REDIS_MAXMEMORY_POLICY}
